services:
  baserow:
    image: 'baserow/baserow:latest'
    environment:
      BASEROW_PUBLIC_URL: '${BASEROW_URL}'
      SECRET_KEY: '${BASEROW_SECRET_KEY}'
    expose:
      - '80'
    volumes:
      - baserow-data:/baserow/data

    restart: unless-stopped

volumes:
  baserow-data:
