services:
  umami:
    image: 'ghcr.io/umami-software/umami:postgresql-latest'
    environment:
      DATABASE_URL: 'postgresql://umami:${UMAMI_DB_PASSWORD}@db:5432/umami'
      APP_SECRET: '${UMAMI_APP_SECRET}'
    expose:
      - '3000'

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: 'umami'
      POSTGRES_USER: 'umami'
      POSTGRES_PASSWORD: '${UMAMI_DB_PASSWORD}'
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  umami-db-data:
