services:
  strapi:
    image: 'strapi/strapi:latest'
    environment:
      DATABASE_CLIENT: 'postgres'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'strapi'
      DATABASE_USERNAME: 'strapi'
      DATABASE_PASSWORD: '${STRAPI_DB_PASSWORD}'
      APP_KEYS: '${STRAPI_APP_KEYS}'
      API_TOKEN_SALT: '${STRAPI_API_TOKEN_SALT}'
      ADMIN_JWT_SECRET: '${STRAPI_ADMIN_JWT_SECRET}'
      JWT_SECRET: '${STRAPI_JWT_SECRET}'
    expose:
      - '1337'
    volumes:
      - strapi-data:/opt/app/data

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: 'strapi'
      POSTGRES_USER: 'strapi'
      POSTGRES_PASSWORD: '${STRAPI_DB_PASSWORD}'
    volumes:
      - strapi-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  strapi-data:
  strapi-db-data:
