services:
  odoo:
    image: 'odoo:17'
    environment:
      HOST: 'db'
      USER: 'odoo'
      PASSWORD: '${ODOO_DB_PASSWORD}'
    expose:
      - '8069'
    volumes:
      - odoo-data:/var/lib/odoo

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'odoo'
      POSTGRES_PASSWORD: '${ODOO_DB_PASSWORD}'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  odoo-data:
  odoo-db-data:
