services:
  papercups:
    image: 'papercups/papercups:latest'
    environment:
      DATABASE_URL: 'postgresql://papercups:${PAPERCUPS_DB_PASSWORD}@db:5432/papercups'
      SECRET_KEY_BASE: '${PAPERCUPS_SECRET_KEY_BASE}'
    expose:
      - '4000'

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: 'papercups'
      POSTGRES_USER: 'papercups'
      POSTGRES_PASSWORD: '${PAPERCUPS_DB_PASSWORD}'
    volumes:
      - papercups-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  papercups-db-data:
