services:
  freescout:
    image: 'tiredofit/freescout:latest'
    environment:
      DB_HOST: 'db'
      DB_NAME: 'freescout'
      DB_USER: 'freescout'
      DB_PASSWORD: '${FREESCOUT_DB_PASSWORD}'
      APP_KEY: '${FREESCOUT_APP_KEY}'
    expose:
      - '80'
    volumes:
      - freescout-data:/data

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'freescout'
      MYSQL_USER: 'freescout'
      MYSQL_PASSWORD: '${FREESCOUT_DB_PASSWORD}'
    volumes:
      - freescout-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  freescout-data:
  freescout-db-data:
