services:
  craft-cms:
    image: 'craftcms/craftcms:latest'
    environment:
      CRAFT_DB_DRIVER: 'mysql'
      CRAFT_DB_SERVER: 'db'
      CRAFT_DB_DATABASE: 'craft'
      CRAFT_DB_USER: 'craft'
      CRAFT_DB_PASSWORD: '${CRAFT_DB_PASSWORD}'
      CRAFT_SECURITY_KEY: '${CRAFT_SECURITY_KEY}'
    expose:
      - '8080'
    volumes:
      - craft-storage:/app/storage

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'mariadb:11'
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: 'craft'
      MARIADB_USER: 'craft'
      MARIADB_PASSWORD: '${CRAFT_DB_PASSWORD}'
    volumes:
      - craft-cms-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","healthcheck.sh","--connect","--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  craft-storage:
  craft-cms-db-data:
