services:
  uptime-kuma:
    cgroup_parent: '${FN_CGROUP_PARENT:-system.slice}'
    image: 'louislam/uptime-kuma:1'
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

volumes:
  uptime-kuma-data:
