services:
  nocodb:
    image: 'nocodb/nocodb:latest'
    environment:
      NC_DB: 'pg://db:5432?u=nocodb&p=${NOCODB_DB_PASSWORD}&d=nocodb'
      NC_AUTH_JWT_SECRET: '${NOCODB_JWT_SECRET}'
    expose:
      - '8080'
    volumes:
      - nocodb-data:/usr/app/data

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: 'nocodb'
      POSTGRES_USER: 'nocodb'
      POSTGRES_PASSWORD: '${NOCODB_DB_PASSWORD}'
    volumes:
      - nocodb-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  nocodb-data:
  nocodb-db-data:
